package org.shorts.model.moves;

public enum Range {
    SINGLE_ADJACENT_ANY,
    SINGLE_ANY,
    SINGLE_ADJACENT_OPPONENT,
    SINGLE_ADJACENT_ALLY,
    SINGLE_SELF_OR_ADJACENT_ALLY,
    SELF,
    OWN_PARTY,
    ALL_ALLIES_EXCEPT_SELF,
    RANDOM_ADJACENT_OPPONENT,
    RANDOM_OPPONENT,
    ALL_ADJACENT_OPPONENTS,
    ALL_ADJACENT,
    ALL,
    BOTH_SIDES,
    OTHER_SIDE,
    OWN_SIDE,
    VARIES
}
